Package suggested git script with Python package
acsone/git-autoshare pull request #15
Opened 2021-10-19 13:25 UTC by joao-p-marques

As suggested in https://github.com/acsone/git-aggregator/pull/55

@sbidoul @Yajo this solves the problem by using a pure Bash script. However, I still haven't found a way of making it optional on install... Any ideas?

Some notes on what was already explored:

1. A Python script to replace the `git` command is not viable due to Python load times.
2. `setuptools` allows you to define optional commands to be insatalled, but AFAIK only through `entry_points`, which is only meant for Python modules.
3. I tried packaging a Python script that would only override `git clone` (`git-clone`) as that would not introduce more delays that `autoshare` itself and it would only affect the `clone` operation. However, even when I have `git-clone` in the path, `git clone` still redirects to the normal command. I guess it is one of those subcommands that can't be replaced...

@Tecnativa 
TT32042

2021-10-21 09:05 UTC, Yajo approved these changes

2021-10-21 11:00 UTC, joao-p-marques commented
@sbidoul Maybe not the most elegant solution, but I just added the option to explicitly opt-in to the script replacement through a shell variable...

2021-10-21 11:06 UTC, Yajo requested changes

2021-10-21 11:06 UTC, Yajo commented on scripts/git
> +if [ $GIT_AUTOSHARE && "$1" == "clone" ]
This ain't python! 😃 

```suggestion
if [ "$GIT_AUTOSHARE" == 1 && "$1" == "clone" ]
```

2021-10-21 11:06 UTC, Yajo commented on README.rst
> +``git autoshare-clone``. To enable it, set the `GIT_AUTOSHARE` variable in your shell to a positive value.
```suggestion
``git autoshare-clone``. To enable it, export `GIT_AUTOSHARE=1` variable in your shell.
```

2021-10-22 06:51 UTC, yajo requested changes

2023-04-12 18:18 UTC, Tardo commented on scripts/git
> +    /usr/bin/git "$@"
Maybe shomething like
```suggestion
    ${$GIT_BIN:-/usr/bin/git} "$@"
```
??

2026-06-11 13:41 UTC, pedrobaeza commented
Please close this PR.

2026-06-11 13:43 UTC, closed without merging